version: 2.1

references:
  defaults: &defaults
    working_directory: ~/app
    docker:
      - image: adrizer/circleci-node-aws:12.13
  yarn_install: &yarn_install
    run:
      name: Install Dependencies
      command: yarn install
  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - v12.13.0-yarn-packages-{{ checksum "yarn.lock" }}
        - v12.13.0-yarn-packages-
  save_yarn_cache: &save_yarn_cache
    save_cache:
      name: Save Yarn Package Cache
      key: v12.13.0-yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run: yarn test

workflows:
  build-test:
    jobs:
      - build
