version: 2.1

references:
  defaults: &defaults
    working_directory: ~/app
    docker:
      - image: cimg/node:14.19.0
        environment:
          MYSQL_DATABASE: lb_cnx_mysql_test
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: password

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: lb_cnx_mysql_test
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: password

  npm_install: &npm_install
    run:
      name: Install Dependencies
      command: npm install
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      name: Restore NPM Package Cache
      keys:
        - v14.19.0-npm-packages-{{ checksum "package-lock.json" }}
        - v14.19.0-npm-packages-
  save_npm_cache: &save_npm_cache
    save_cache:
      name: Save NPM Package Cache
      key: v14.19.0-npm-packages-{{ checksum "package-lock.json" }}
      paths:
        - ~/.cache/npm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *npm_install
      - *save_npm_cache
      - run: npm test

workflows:
  build-test:
    jobs:
      - build
